# 语言 Language 可选 Optional: lang_en lang_cn lang_ru
language: "lang_cn"

# 设置
setting:
  # 如果是new，右键工作台时打开自定义矩阵合成系统
  # 如果是sel，右键工作台时打开原版合成系统-自定义矩阵合成系统选择界面
  # 如果是old，右键工作台时打开原版合成系统
  default: sel
  # 如果打开新型合成系统
  # 打开的GUI的合成面板ID
  gui: gui
# 关于合成系统菜单
inventory:
  # 合成系统标题
  title: '&l合成系统'
  # 点击合成按钮的名称
  button: '&7&l[&a点击合成&7&l]'
  # 关闭按钮的名称
  close: '&7&l[&c关闭&7&l]'
# 关于选择界面 About selection Gui
selectGui:
  title: "&l请选择合成系统"
  vanillaGuiButton: "&7&l[&a原版合成系统&7&l]"
  newGuiButton: "&7&l[&a新型合成系统&7&l]"