name: CustCraft
version: '${version}'
main: cn.mscraft.custcraft.CustCraft
api-version: 1.20
authors: [ curii, Remering ]
depend: [ NBTAPI ]
commands:
  custcraft:
    description: command
    usage: /<command>
    aliases:
      - ct
